# Generated by Django 5.1.4 on 2024-12-30 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(max_length=100)),
                ('qualifications', models.TextField()),
                ('institutions_attended', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='registrations/photos/')),
                ('birth_certificate', models.FileField(upload_to='registrations/certificates/')),
                ('education_certificates', models.FileField(upload_to='registrations/certificates/')),
                ('payment_proof', models.FileField(upload_to='registrations/payments/')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
