# Generated by Django 5.1.4 on 2024-12-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_registration_remove_registration2_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='start_date',
        ),
    ]
