# Generated by Django 5.1.4 on 2024-12-30 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
