# Generated by Django 5.1.4 on 2024-12-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
