# Generated by Django 5.1.4 on 2024-12-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_registration_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
    ]
