# Generated by Django 5.1.4 on 2024-12-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_registration_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
