# Generated by Django 5.1.4 on 2024-12-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='settled',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Paystack', 'Paystack'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], default='Paystack', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='program_title',
            field=models.CharField(choices=[('Mining Level 3', 'Occupational Standards for Mining and Quarrying Technology National Certificate I (Level 3)'), ('Mines Engineering Level 4', 'Occupational Standards for Mines Systems Engineering National Certificate 2 (Level 4)'), ('Mines Engineering Diploma Level 5', 'Occupational Standards for Higher National Diploma in Mines Systems Engineering (Level 5)')], max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
