# Generated by Django 5.1.4 on 2025-01-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_transaction_settled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='proof_of_payment',
        ),
    ]
