# Generated by Django 5.1.4 on 2025-06-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_remove_registration_proof_of_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="approved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="rejected_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="rejection_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
