# Generated by Django 5.1.4 on 2025-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_registration_approved_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
